development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Agaex
  admin_email: josparbar@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Agaex
  admin_email: agaex@agaex.com
